service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 720
  timeout: 900

functions:
  getAuctionUrl:
    handler: auction.handler
    events:
      - http:
          method: post
          path: auction
          cors:
            origin: '*'

  getItems:
    handler: item.handler
    events:
      - http:
          method: any
          path: item
          cors:
            origin: '*'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: '*'

  test:
    handler: test.handler
    events:
      - http:
          method: any
          path: test
