service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 200
  timeout: 59

functions:
  auctions:
    handler: src/controllers/auction.handler
    memorySize: 512
    events:
      - http:
          method: post
          path: auction
          cors:
            origin: '*'
  auctionUpdateLogForRealm:
    handler: src/controllers/auction.getUpdateLogForRealm
    memorySize: 128
    events:
      - http:
          method: get
          path: auction/log/{id}
          cors:
            origin: '*'
  auctionsS3:
    handler: src/controllers/auction.s3
    events:
      - http:
          method: post
          path: auction/s3
          cors:
            origin: '*'
  updateAllHouses:
    handler: src/controllers/auction.updateAll
    memorySize: 200
    events:
      - http:
          method: any
          path: auction/update
          cors:
            origin: '*'

  deactivateInactiveHouses:
    handler: src/controllers/auction.deactivateInactiveHouses
    memorySize: 200
    events:
      - http:
          method: any
          path: auction/deactivate
          cors:
            origin: '*'

  updateSpesificHouse:
    handler: src/controllers/auction.updateOne
    memorySize: 512
    events:
      - http:
          method: post
          path: auction/update-one
          cors:
            origin: '*'
  locales:
    handler: src/controllers/locale.handler
    events:
      - http:
          method: post
          path: locale/add-missing
          cors:
            origin: 'localhost:3000'
  items:
    handler: src/controllers/item.handler
    memorySize: 160
    events:
      - http:
          method: any
          path: item
          cors:
            origin: '*'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: '*'
  pets:
    handler: src/controllers/pet.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: pet
          cors:
            origin: '*'

      - http:
          method: any
          path: pet/{id}
          cors:
            origin: '*'
  recipes:
    handler: src/controllers/recipe.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: recipe
          cors:
            origin: '*'

      - http:
          method: any
          path: recipe/{id}
          cors:
            origin: '*'
  character:
    handler: src/controllers/character.handler
    memorySize: 128
    events:
      - http:
          method: post
          path: character
          cors:
            origin: '*'
  realm:
    handler: src/controllers/realm.handler
    events:
      - http:
          method: post
          path: realm
          cors:
            origin: '*'
  realmAllRegions:
    handler: src/controllers/realm.handleGetAll
    memorySize: 128
    events:
      - http:
          method: get
          path: realm/all
          cors:
            origin: '*'
  getByRegionAndName:
    handler: src/controllers/realm.getByRegionAndName
    memorySize: 128
    events:
      - http:
          method: get
          path: realm/{region}/{realm}
          cors:
            origin: '*'
  test:
    handler: src/controllers/test.handler
    events:
      - http:
          method: any
          path: test

  logger:
    handler: src/controllers/logger.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: logger
  loggerClientEvent:
    handler: src/controllers/logger.clientEvent
    memorySize: 128
    events:
      - http:
          method: post
          path: logger/client-event

  loggerClientDelete:
    handler: src/controllers/logger.clientDelete
    memorySize: 128
    events:
      - http:
          method: delete
          path: logger/client-event
          cors:
            origin: '*'
