service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 200
  timeout: 30
  tags:
    Project: WAH
  tracing:
    apiGateway: true
    lambda: true

functions:
  auctions:
    tags:
      Lambda: Wah-auctions
    handler: src/controllers/auction.handler
    memorySize: 512
    events:
      - http:
          method: post
          path: auction
          cors:
            origin: '*'
  auctionUpdateLogForRealm:
    tags:
      Lambda: Wah-auctionUpdateLogForRealm
    handler: src/controllers/auction.getUpdateLogForRealm
    memorySize: 128
    events:
      - http:
          method: get
          path: auction/log/{id}
          cors:
            origin: '*'
  auctionsS3:
    tags:
      Lambda: Wah-auctionsS3
    handler: src/controllers/auction.s3
    events:
      - http:
          method: post
          path: auction/s3
          cors:
            origin: '*'
  updateAllHouses:
    tags:
      Lambda: Wah-updateAllHouses
    handler: src/controllers/auction.updateAll
    memorySize: 200
    events:
      - http:
          method: any
          path: auction/update
          cors:
            origin: '*'

  deactivateInactiveHouses:
    tags:
      Lambda: Wah-deactivateInactiveHouses
    handler: src/controllers/auction.deactivateInactiveHouses
    memorySize: 200
    events:
      - http:
          method: any
          path: auction/deactivate
          cors:
            origin: '*'

  updateSpesificHouse:
    tags:
      Lambda: Wah-updateSpesificHouse
    handler: src/controllers/auction.updateOne
    memorySize: 512
    events:
      - http:
          method: post
          path: auction/update-one
          cors:
            origin: '*'
  locales:
    tags:
      Lambda: Wah-locales
    handler: src/controllers/locale.handler
    events:
      - http:
          method: post
          path: locale/add-missing
          cors:
            origin: 'localhost:3000'
  items:
    tags:
      Lambda: Wah-items
    handler: src/controllers/item.handler
    memorySize: 160
    events:
      - http:
          method: any
          path: item
          cors:
            origin: '*'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: '*'
  pets:
    tags:
      Lambda: Wah-pets
    handler: src/controllers/pet.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: pet
          cors:
            origin: '*'

      - http:
          method: any
          path: pet/{id}
          cors:
            origin: '*'
  recipes:
    tags:
      Lambda: Wah-recipes
    handler: src/controllers/recipe.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: recipe
          cors:
            origin: '*'

      - http:
          method: any
          path: recipe/{id}
          cors:
            origin: '*'
  zone:
    tags:
      Lambda: Wah-zone
    handler: src/controllers/zone.getAll
    memorySize: 128
    timeout: 60
    events:
      - http:
          method: post
          path: zone
          cors:
            origin: 'http://localhost:4200'
  npcGetById:
    tags:
      Lambda: Wah-npc-by-id
    handler: src/controllers/npc.getById
    memorySize: 128
    events:
      - http:
          method: post
          path: npc/{id}
          cors:
            origin: '*'
  npcGetAll:
    tags:
      Lambda: Wah-npc-get-all
    handler: src/controllers/npc.getAll
    memorySize: 1024
    events:
      - http:
          method: post
          path: npc/all
          cors:
            origin: 'http://localhost:4200'
  npcGetByIds:
    tags:
      Lambda: Wah-npc
    handler: src/controllers/npc.addNewNPCsByIds
    memorySize: 256
    timeout: 30
    events:
      - http:
          method: post
          path: npc
          cors:
            origin: 'http://localhost:4200'
  character:
    tags:
      Lambda: Wah-character
    handler: src/controllers/character.handler
    memorySize: 128
    events:
      - http:
          method: post
          path: character
          cors:
            origin: '*'
  realm:
    tags:
      Lambda: Wah-realm
    handler: src/controllers/realm.handler
    events:
      - http:
          method: post
          path: realm
          cors:
            origin: '*'
  realmAllRegions:
    tags:
      Lambda: Wah-realmAllRegions
    handler: src/controllers/realm.handleGetAll
    memorySize: 128
    events:
      - http:
          method: get
          path: realm/all
          cors:
            origin: '*'
  getByRegionAndName:
    tags:
      Lambda: Wah-getByRegionAndName
    handler: src/controllers/realm.getByRegionAndName
    memorySize: 128
    events:
      - http:
          method: get
          path: realm/{region}/{realm}
          cors:
            origin: '*'
  test:
    tags:
      Lambda: Wah-test
    handler: src/controllers/test.handler
    events:
      - http:
          method: any
          path: test

  logger:
    tags:
      Lambda: Wah-logger
    handler: src/controllers/logger.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: logger
  loggerClientEvent:
    tags:
      Lambda: Wah-loggerClientEvent
    handler: src/controllers/logger.clientEvent
    memorySize: 128
    events:
      - http:
          method: post
          path: logger/client-event

  loggerClientDelete:
    tags:
      Lambda: Wah-loggerClientDelete
    handler: src/controllers/logger.clientDelete
    memorySize: 128
    events:
      - http:
          method: delete
          path: logger/client-event
          cors:
            origin: '*'
  currency:
    tags:
      Lambda: Wah-currencies
    handler: src/controllers/currency.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: currency
          cors:
            origin: 'http://localhost:4200'
